### ISSUE TITLE
How do users redeem?

### ISSUE THREAD

**Issue by krippee** [byteweaver/django-coupons#20]
I do not see any save methods or anything in the code. The closest I can find is the redeem function in the model for `Coupon`.  Can you provide some guidance as to how a user can actually redeem their code?

**Comment by Akuryou** [comment]
Hi,

that depends on your implementation and what you want to do.

Check out coupons.foms.CouponForm if you want do display a form to your users.
If it is valid, redeem the coupon.

Sorry for the lack of documentation, I didn't have enough time to do that yet.

**Comment by krippee** [comment]
That is exactly what I am trying to do, have a user redeem the coupon via the CouponForm. I will have it do a bit more logic once the coupon is redeemed. The problem I am having is trying to figure out how exactly to redeem the code. I tried calling:

```
redeem = CouponForm(request.POST)
            if redeem.is_valid():
                redeem.clean_code()
```

but that seems to do nothing at all. I feel like I must be missing something obvious but I cannot put my finger on it.

Thanks!

**Comment by krippee** [comment]
Also, while I am busy with Q4 work and currently building out this application I am working on when I am done I would be happy to write out some documentation (if I can get this figured out that is :P)

**Comment by Akuryou** [comment]
ah now I get your problem.

Have a look at the django forms documentation.
clean_<field_name> are special methods that will be called by is_valid().
you don't have to call them yourself.

try:

```
form = CouponForm(request.POST)
coupon = form.is_valid()
coupon.redeem(request.user)
```

furthermore `form.is_valid()` will raise validation errors if the coupon is not valid.

**Comment by krippee** [comment]
Okay, I tried that and now I am getting the following error:

`'bool' object has no attribute 'redeem'`

I checked in my DB and there does not seem to be a redeem field as the error would suggest...which is strange as I ran all of the migrations.

**Comment by krippee** [comment]
Could you maybe give me and example view to look at so I can try and figure out what I am doing wrong here? The above code that you gave me is not working either.

**Comment by krippee** [comment]
```
def gift_card(request):

    user = request.user

    if request.user.is_authenticated:
        edit_profile = EditProfileForm(user=user)
        redeem = CouponForm()
        if request.method == 'POST':
            edit_profile = EditProfileForm(request.POST, user=user)
            redeem = CouponForm(request.POST, user=user)
            if redeem.is_valid():
                coupon = redeem.coupon
                coupon.redeem(request.user)
            else:
                pass
            return render(request, 'main/profile.html', {'edit_profile': edit_profile, 'redeem': redeem})

        return render(request, 'main/profile.html', {'edit_profile': edit_profile, 'redeem': redeem})
    else:
        return redirect('/')
```

Worked!
